insert into sources (type, config, category, locale, enabled) values
  ('hacker_news', '{"list": "topstories", "limit": "25"}', 'it', 'pl', true),
  ('hacker_news', '{"list": "topstories", "limit": "25"}', 'it', 'en', false),
  ('hacker_news', '{"list": "topstories", "limit": "25"}', 'ai', 'pl', true),
  ('hacker_news', '{"list": "topstories", "limit": "25"}', 'ai', 'en', false),
  ('lobsters', '{"tag": "programming"}', 'it', 'pl', true),
  ('lobsters', '{"tag": "programming"}', 'it', 'en', false),
  ('lobsters', '{"tag": "compsci"}', 'ai', 'pl', true),
  ('lobsters', '{"tag": "compsci"}', 'ai', 'en', false),
  ('lobsters', '{"tag": "culture"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://hnrss.org/newest?q=game+OR+gaming&points=50"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.rockpapershotgun.com/feed"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://techcrunch.com/feed/"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://www.theverge.com/rss/index.xml"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://feeds.arstechnica.com/arstechnica/index"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://www.wired.com/feed/rss"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://spidersweb.pl/feed"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://antyweb.pl/feed"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://www.technologyreview.com/feed/"}', 'ai', 'pl', true),
  ('rss', '{"feedUrl": "https://www.eurogamer.net/feed"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.polygon.com/rss/index.xml"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.benchmark.pl/rss/aktualnosci.xml"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://dev.to/feed"}', 'it', 'pl', true),
  ('rss', '{"feedUrl": "https://www.theregister.com/headlines.atom"}', 'it', 'pl', true),
  ('rss', '{"feedUrl": "https://feeds.feedburner.com/TheHackersNews"}', 'it', 'pl', true),
  ('rss', '{"feedUrl": "https://hnrss.org/newest?q=security&points=50"}', 'it', 'pl', true),
  ('rss', '{"feedUrl": "https://www.chip.pl/rss/"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://www.dobreprogramy.pl/rss/aktualnosci"}', 'tech', 'pl', true),
  ('rss', '{"feedUrl": "https://blog.google/technology/ai/rss/"}', 'ai', 'pl', true),
  ('rss', '{"feedUrl": "https://openai.com/blog/rss.xml"}', 'ai', 'pl', true),
  ('rss', '{"feedUrl": "https://hnrss.org/newest?q=AI+OR+LLM&points=30"}', 'ai', 'pl', true),
  ('rss', '{"feedUrl": "https://www.pcgamer.com/rss/"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.gamespot.com/feeds/mashup/"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.ign.com/rss/articles/feed"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.gry-online.pl/rss/news.xml"}', 'gaming', 'pl', true),
  ('rss', '{"feedUrl": "https://www.espn.com/espn/rss/news"}', 'sport', 'pl', true),
  ('rss', '{"feedUrl": "https://feeds.bbci.co.uk/sport/rss.xml"}', 'sport', 'pl', true),
  ('rss', '{"feedUrl": "https://www.coindesk.com/arc/outboundfeeds/rss/"}', 'finance', 'pl', true),
  ('rss', '{"feedUrl": "https://feeds.bloomberg.com/markets/news.rss"}', 'finance', 'pl', true),
  ('rss', '{"feedUrl": "https://www.bankier.pl/rss/wiadomosci.xml"}', 'finance', 'pl', true),
  ('youtube', '{"category": "technology", "regionCode": "PL"}', 'tech', 'pl', true),
  ('youtube', '{"category": "gaming", "regionCode": "PL"}', 'gaming', 'pl', true);

-- Reddit disabled until API approval (Responsible Builder Policy)
-- ('reddit', '{"subreddit": "technology"}', 'tech', 'pl', false),
